/**
 * Copyright (c) 2025 OpenShort.link Contributors
 *
 * Licensed under the GNU Affero General Public License Version 3 (AGPL-3.0)
 * See LICENSE file or https://www.gnu.org/licenses/agpl-3.0.txt
 */

/**
 * Comprehensive country name to ISO 3166-1 alpha-2 code mappings
 * Supports: full names (with spaces), 2-letter codes, underscores, hyphens, aliases
 */

export const COUNTRY_MAPPINGS: Record<string, string> = {
  // ===== 2-LETTER ISO CODES (lowercase for matching) =====
  'us': 'US',
  'gb': 'GB',
  'ca': 'CA',
  'au': 'AU',
  'de': 'DE',
  'fr': 'FR',
  'it': 'IT',
  'es': 'ES',
  'jp': 'JP',
  'cn': 'CN',
  'in': 'IN',
  'br': 'BR',
  'mx': 'MX',
  'nl': 'NL',
  'se': 'SE',
  'no': 'NO',
  'dk': 'DK',
  'fi': 'FI',
  'pl': 'PL',
  'ru': 'RU',
  'kr': 'KR',
  'tr': 'TR',
  'sa': 'SA',
  'ae': 'AE',
  'il': 'IL',
  'eg': 'EG',
  'za': 'ZA',
  'nz': 'NZ',
  'sg': 'SG',
  'hk': 'HK',
  'my': 'MY',
  'th': 'TH',
  'id': 'ID',
  'ph': 'PH',
  'vn': 'VN',
  'ar': 'AR',
  'cl': 'CL',
  'co': 'CO',
  've': 'VE',
  'pe': 'PE',
  'at': 'AT',
  'be': 'BE',
  'ch': 'CH',
  'cz': 'CZ',
  'gr': 'GR',
  'ie': 'IE',
  'pt': 'PT',
  'ro': 'RO',
  'hu': 'HU',
  'bg': 'BG',
  'sk': 'SK',
  'hr': 'HR',
  'si': 'SI',
  'lt': 'LT',
  'lv': 'LV',
  'ee': 'EE',
  'ua': 'UA',
  'by': 'BY',
  'rs': 'RS',
  'ba': 'BA',
  'mk': 'MK',
  'al': 'AL',
  'is': 'IS',
  'lu': 'LU',
  'mt': 'MT',
  'cy': 'CY',
  'ng': 'NG',
  'ke': 'KE',
  'gh': 'GH',
  'tz': 'TZ',
  'ug': 'UG',
  'et': 'ET',
  'ma': 'MA',
  'dz': 'DZ',
  'tn': 'TN',
  'ly': 'LY',
  'sd': 'SD',
  'ao': 'AO',
  'mz': 'MZ',
  'zw': 'ZW',
  'bw': 'BW',
  'na': 'NA',
  'mw': 'MW',
  'zm': 'ZM',
  'sn': 'SN',
  'ci': 'CI',
  'cm': 'CM',
  'bd': 'BD',
  'pk': 'PK',
  'lk': 'LK',
  'np': 'NP',
  'mm': 'MM',
  'kh': 'KH',
  'la': 'LA',
  'mn': 'MN',
  'kz': 'KZ',
  'uz': 'UZ',
  'ge': 'GE',
  'am': 'AM',
  'az': 'AZ',
  'iq': 'IQ',
  'ir': 'IR',
  'jo': 'JO',
  'kw': 'KW',
  'lb': 'LB',
  'om': 'OM',
  'qa': 'QA',
  'sy': 'SY',
  'ye': 'YE',
  'bh': 'BH',
  'ec': 'EC',
  'uy': 'UY',
  'py': 'PY',
  'bo': 'BO',
  'cr': 'CR',
  'pa': 'PA',
  'gt': 'GT',
  'hn': 'HN',
  'ni': 'NI',
  'sv': 'SV',
  'do': 'DO',
  'cu': 'CU',
  'jm': 'JM',
  'tt': 'TT',
  'bs': 'BS',
  'bb': 'BB',
  'gy': 'GY',
  'sr': 'SR',
  'bz': 'BZ',
  'fj': 'FJ',
  'pg': 'PG',
  
  // ===== COMMON ALIASES =====
  'usa': 'US',
  'uk': 'GB',
  'britain': 'GB',
  'england': 'GB',
  'deutschland': 'DE',
  'nippon': 'JP',
  'aussie': 'AU',
  'kiwi': 'NZ',
  'uae': 'AE',
  'korea': 'KR',
  'holland': 'NL',
  
  // ===== FULL NAMES WITH SPACES (lowercase) =====
  'united states': 'US',
  'united kingdom': 'GB',
  'canada': 'CA',
  'australia': 'AU',
  'germany': 'DE',
  'france': 'FR',
  'italy': 'IT',
  'spain': 'ES',
  'japan': 'JP',
  'china': 'CN',
  'india': 'IN',
  'brazil': 'BR',
  'mexico': 'MX',
  'netherlands': 'NL',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'poland': 'PL',
  'russia': 'RU',
  'south korea': 'KR',
  'turkey': 'TR',
  'saudi arabia': 'SA',
  'united arab emirates': 'AE',
  'israel': 'IL',
  'egypt': 'EG',
  'south africa': 'ZA',
  'new zealand': 'NZ',
  'singapore': 'SG',
  'hong kong': 'HK',
  'malaysia': 'MY',
  'thailand': 'TH',
  'indonesia': 'ID',
  'philippines': 'PH',
  'vietnam': 'VN',
  'argentina': 'AR',
  'chile': 'CL',
  'colombia': 'CO',
  'venezuela': 'VE',
  'peru': 'PE',
  'austria': 'AT',
  'belgium': 'BE',
  'switzerland': 'CH',
  'czech republic': 'CZ',
  'greece': 'GR',
  'ireland': 'IE',
  'portugal': 'PT',
  'romania': 'RO',
  'hungary': 'HU',
  'bulgaria': 'BG',
  'slovakia': 'SK',
  'croatia': 'HR',
  'slovenia': 'SI',
  'lithuania': 'LT',
  'latvia': 'LV',
  'estonia': 'EE',
  'ukraine': 'UA',
  'belarus': 'BY',
  'serbia': 'RS',
  'bosnia': 'BA',
  'bosnia and herzegovina': 'BA',
  'macedonia': 'MK',
  'albania': 'AL',
  'iceland': 'IS',
  'luxembourg': 'LU',
  'malta': 'MT',
  'cyprus': 'CY',
  'nigeria': 'NG',
  'kenya': 'KE',
  'ghana': 'GH',
  'tanzania': 'TZ',
  'uganda': 'UG',
  'ethiopia': 'ET',
  'morocco': 'MA',
  'algeria': 'DZ',
  'tunisia': 'TN',
  'libya': 'LY',
  'sudan': 'SD',
  'angola': 'AO',
  'mozambique': 'MZ',
  'zimbabwe': 'ZW',
  'botswana': 'BW',
  'namibia': 'NA',
  'malawi': 'MW',
  'zambia': 'ZM',
  'senegal': 'SN',
  'ivory coast': 'CI',
  'cameroon': 'CM',
  'bangladesh': 'BD',
  'pakistan': 'PK',
  'sri lanka': 'LK',
  'nepal': 'NP',
  'myanmar': 'MM',
  'cambodia': 'KH',
  'laos': 'LA',
  'mongolia': 'MN',
  'kazakhstan': 'KZ',
  'uzbekistan': 'UZ',
  'georgia': 'GE',
  'armenia': 'AM',
  'azerbaijan': 'AZ',
  'iraq': 'IQ',
  'iran': 'IR',
  'jordan': 'JO',
  'kuwait': 'KW',
  'lebanon': 'LB',
  'oman': 'OM',
  'qatar': 'QA',
  'syria': 'SY',
  'yemen': 'YE',
  'bahrain': 'BH',
  'ecuador': 'EC',
  'uruguay': 'UY',
  'paraguay': 'PY',
  'bolivia': 'BO',
  'costa rica': 'CR',
  'panama': 'PA',
  'guatemala': 'GT',
  'honduras': 'HN',
  'nicaragua': 'NI',
  'el salvador': 'SV',
  'dominican republic': 'DO',
  'cuba': 'CU',
  'jamaica': 'JM',
  'trinidad and tobago': 'TT',
  'trinidad': 'TT',
  'tobago': 'TT',
  'bahamas': 'BS',
  'barbados': 'BB',
  'guyana': 'GY',
  'suriname': 'SR',
  'belize': 'BZ',
  'fiji': 'FJ',
  'papua new guinea': 'PG',
  
  // ===== FULL NAMES WITH UNDERSCORES =====
  'united_states': 'US',
  'united_kingdom': 'GB',
  'south_korea': 'KR',
  'new_zealand': 'NZ',
  'saudi_arabia': 'SA',
  'united_arab_emirates': 'AE',
  'south_africa': 'ZA',
  'hong_kong': 'HK',
  'czech_republic': 'CZ',
  'bosnia_and_herzegovina': 'BA',
  'sri_lanka': 'LK',
  'costa_rica': 'CR',
  'el_salvador': 'SV',
  'dominican_republic': 'DO',
  'trinidad_and_tobago': 'TT',
  'papua_new_guinea': 'PG',
  'ivory_coast': 'CI',
  
  // ===== FULL NAMES WITH HYPHENS =====
  'united-states': 'US',
  'united-kingdom': 'GB',
  'south-korea': 'KR',
  'new-zealand': 'NZ',
  'saudi-arabia': 'SA',
  'united-arab-emirates': 'AE',
  'south-africa': 'ZA',
  'hong-kong': 'HK',
  'czech-republic': 'CZ',
  'bosnia-and-herzegovina': 'BA',
  'sri-lanka': 'LK',
  'costa-rica': 'CR',
  'el-salvador': 'SV',
  'dominican-republic': 'DO',
  'trinidad-and-tobago': 'TT',
  'papua-new-guinea': 'PG',
  'ivory-coast': 'CI',
  
  // ===== FULL NAMES WITHOUT SEPARATORS (normalized) =====
  'unitedstates': 'US',
  'unitedkingdom': 'GB',
  'southkorea': 'KR',
  'newzealand': 'NZ',
  'saudiarabia': 'SA',
  'unitedarabemirates': 'AE',
  'southafrica': 'ZA',
  'hongkong': 'HK',
  'czechrepublic': 'CZ',
  'bosniaandherzegovina': 'BA',
  'srilanka': 'LK',
  'costarica': 'CR',
  'elsalvador': 'SV',
  'dominicanrepublic': 'DO',
  'trinidadandtobago': 'TT',
  'papuanewguinea': 'PG',
  'ivorycoast': 'CI',
};

/**
 * Detects country code from a column header
 * Supports all naming patterns: spaces, underscores, hyphens, suffixes, etc.
 */
export function detectCountryCode(header: string): string | null {
  const original = header.trim();
  let clean = original.toLowerCase();
  
  // All suffixes to recognize and strip
  const suffixes = [
    ' url',   // "United States URL"
    ' link',  // "United States Link"
    ' page',  // "United States Page"
    '_url',   // "united_states_url" or "us_url"
    '_link',  // "united_states_link" or "us_link"
    '_page',  // "united_states_page"
    '-url',   // "united-states-url" or "us-url"
    '-link',  // "united-states-link"
    '-page',  // "united-states-page"
    'url',    // "unitedstatesurl" (no separator)
    'link',   // "unitedstateslink"
    'page',   // "unitedstatespage"
  ];
  
  // Try removing each suffix
  let withoutSuffix = clean;
  for (const suffix of suffixes) {
    if (clean.endsWith(suffix)) {
      withoutSuffix = clean.slice(0, -suffix.length).trim();
      // Remove trailing separator if any
      withoutSuffix = withoutSuffix.replace(/[_-]+$/, '');
      break;
    }
  }
  
  // Strategy 1: Try exact match (preserves spaces/separators)
  if (COUNTRY_MAPPINGS[withoutSuffix]) {
    return COUNTRY_MAPPINGS[withoutSuffix];
  }
  
  // Strategy 2: Try with spaces converted to underscores
  const withUnderscores = withoutSuffix.replace(/\s+/g, '_');
  if (COUNTRY_MAPPINGS[withUnderscores]) {
    return COUNTRY_MAPPINGS[withUnderscores];
  }
  
  // Strategy 3: Try with spaces converted to hyphens
  const withHyphens = withoutSuffix.replace(/\s+/g, '-');
  if (COUNTRY_MAPPINGS[withHyphens]) {
    return COUNTRY_MAPPINGS[withHyphens];
  }
  
  // Strategy 4: Try normalized (remove ALL spaces/separators)
  const normalized = withoutSuffix.replace(/[\s_-]/g, '');
  if (COUNTRY_MAPPINGS[normalized]) {
    return COUNTRY_MAPPINGS[normalized];
  }
  
  // Strategy 5: If exactly 2 characters, check if valid country code
  if (withoutSuffix.length === 2) {
    const upperCode = withoutSuffix.toUpperCase();
    if (COUNTRY_MAPPINGS[withoutSuffix]) {
      return upperCode;
    }
  }
  
  return null;
}

/**
 * Get human-readable country name from ISO code
 */
export function getCountryName(countryCode: string): string {
  const countryNames: Record<string, string> = {
    'US': 'United States',
    'GB': 'United Kingdom',
    'CA': 'Canada',
    'AU': 'Australia',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'JP': 'Japan',
    'CN': 'China',
    'IN': 'India',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'PL': 'Poland',
    'RU': 'Russia',
    'KR': 'South Korea',
    'TR': 'Turkey',
    'SA': 'Saudi Arabia',
    'AE': 'United Arab Emirates',
    'IL': 'Israel',
    'EG': 'Egypt',
    'ZA': 'South Africa',
    'NZ': 'New Zealand',
    'SG': 'Singapore',
    'HK': 'Hong Kong',
    'MY': 'Malaysia',
    'TH': 'Thailand',
    'ID': 'Indonesia',
    'PH': 'Philippines',
    'VN': 'Vietnam',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'VE': 'Venezuela',
    'PE': 'Peru',
    'AT': 'Austria',
    'BE': 'Belgium',
    'CH': 'Switzerland',
    'CZ': 'Czech Republic',
    'GR': 'Greece',
    'IE': 'Ireland',
    'PT': 'Portugal',
    'RO': 'Romania',
    'HU': 'Hungary',
    'BG': 'Bulgaria',
    'SK': 'Slovakia',
    'HR': 'Croatia',
    'SI': 'Slovenia',
    'LT': 'Lithuania',
    'LV': 'Latvia',
    'EE': 'Estonia',
    'UA': 'Ukraine',
    'BY': 'Belarus',
    'RS': 'Serbia',
    'BA': 'Bosnia and Herzegovina',
    'MK': 'Macedonia',
    'AL': 'Albania',
    'IS': 'Iceland',
    'LU': 'Luxembourg',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'NG': 'Nigeria',
    'KE': 'Kenya',
    'GH': 'Ghana',
    'TZ': 'Tanzania',
    'UG': 'Uganda',
    'ET': 'Ethiopia',
    'MA': 'Morocco',
    'DZ': 'Algeria',
    'TN': 'Tunisia',
    'LY': 'Libya',
    'SD': 'Sudan',
    'AO': 'Angola',
    'MZ': 'Mozambique',
    'ZW': 'Zimbabwe',
    'BW': 'Botswana',
    'NA': 'Namibia',
    'MW': 'Malawi',
    'ZM': 'Zambia',
    'SN': 'Senegal',
    'CI': 'Ivory Coast',
    'CM': 'Cameroon',
    'BD': 'Bangladesh',
    'PK': 'Pakistan',
    'LK': 'Sri Lanka',
    'NP': 'Nepal',
    'MM': 'Myanmar',
    'KH': 'Cambodia',
    'LA': 'Laos',
    'MN': 'Mongolia',
    'KZ': 'Kazakhstan',
    'UZ': 'Uzbekistan',
    'GE': 'Georgia',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'IQ': 'Iraq',
    'IR': 'Iran',
    'JO': 'Jordan',
    'KW': 'Kuwait',
    'LB': 'Lebanon',
    'OM': 'Oman',
    'QA': 'Qatar',
    'SY': 'Syria',
    'YE': 'Yemen',
    'BH': 'Bahrain',
    'EC': 'Ecuador',
    'UY': 'Uruguay',
    'PY': 'Paraguay',
    'BO': 'Bolivia',
    'CR': 'Costa Rica',
    'PA': 'Panama',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'NI': 'Nicaragua',
    'SV': 'El Salvador',
    'DO': 'Dominican Republic',
    'CU': 'Cuba',
    'JM': 'Jamaica',
    'TT': 'Trinidad and Tobago',
    'BS': 'Bahamas',
    'BB': 'Barbados',
    'GY': 'Guyana',
    'SR': 'Suriname',
    'BZ': 'Belize',
    'FJ': 'Fiji',
    'PG': 'Papua New Guinea',
  };
  
  return countryNames[countryCode] || countryCode;
}

